//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TrainingRoomAppDBModel", "FK__tblCampus__Locat__09DE7BCC", "tblLocation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TrainingRoomEF.tblLocation), "tblCampu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TrainingRoomEF.tblCampu), true)]

#endregion

namespace TrainingRoomEF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TrainingRoomAppDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TrainingRoomAppDBEntities object using the connection string found in the 'TrainingRoomAppDBEntities' section of the application configuration file.
        /// </summary>
        public TrainingRoomAppDBEntities() : base("name=TrainingRoomAppDBEntities", "TrainingRoomAppDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TrainingRoomAppDBEntities object.
        /// </summary>
        public TrainingRoomAppDBEntities(string connectionString) : base(connectionString, "TrainingRoomAppDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TrainingRoomAppDBEntities object.
        /// </summary>
        public TrainingRoomAppDBEntities(EntityConnection connection) : base(connection, "TrainingRoomAppDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCampu> tblCampus
        {
            get
            {
                if ((_tblCampus == null))
                {
                    _tblCampus = base.CreateObjectSet<tblCampu>("tblCampus");
                }
                return _tblCampus;
            }
        }
        private ObjectSet<tblCampu> _tblCampus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblLocation> tblLocations
        {
            get
            {
                if ((_tblLocations == null))
                {
                    _tblLocations = base.CreateObjectSet<tblLocation>("tblLocations");
                }
                return _tblLocations;
            }
        }
        private ObjectSet<tblLocation> _tblLocations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbltrainingRoomDetail> tbltrainingRoomDetails
        {
            get
            {
                if ((_tbltrainingRoomDetails == null))
                {
                    _tbltrainingRoomDetails = base.CreateObjectSet<tbltrainingRoomDetail>("tbltrainingRoomDetails");
                }
                return _tbltrainingRoomDetails;
            }
        }
        private ObjectSet<tbltrainingRoomDetail> _tbltrainingRoomDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSlot> tblSlots
        {
            get
            {
                if ((_tblSlots == null))
                {
                    _tblSlots = base.CreateObjectSet<tblSlot>("tblSlots");
                }
                return _tblSlots;
            }
        }
        private ObjectSet<tblSlot> _tblSlots;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblReview> tblReviews
        {
            get
            {
                if ((_tblReviews == null))
                {
                    _tblReviews = base.CreateObjectSet<tblReview>("tblReviews");
                }
                return _tblReviews;
            }
        }
        private ObjectSet<tblReview> _tblReviews;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCampus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCampus(tblCampu tblCampu)
        {
            base.AddObject("tblCampus", tblCampu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblLocations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblLocations(tblLocation tblLocation)
        {
            base.AddObject("tblLocations", tblLocation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbltrainingRoomDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbltrainingRoomDetails(tbltrainingRoomDetail tbltrainingRoomDetail)
        {
            base.AddObject("tbltrainingRoomDetails", tbltrainingRoomDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSlots EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSlots(tblSlot tblSlot)
        {
            base.AddObject("tblSlots", tblSlot);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblReviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblReviews(tblReview tblReview)
        {
            base.AddObject("tblReviews", tblReview);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetLocation_Types> procGetLocation()
        {
            return base.ExecuteFunction<GetLocation_Types>("procGetLocation");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="locationName">No Metadata Documentation available.</param>
        public ObjectResult<procGetCampus_Types> procGetCampus(global::System.String locationName)
        {
            ObjectParameter locationNameParameter;
            if (locationName != null)
            {
                locationNameParameter = new ObjectParameter("LocationName", locationName);
            }
            else
            {
                locationNameParameter = new ObjectParameter("LocationName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<procGetCampus_Types>("procGetCampus", locationNameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="locationName">No Metadata Documentation available.</param>
        /// <param name="campusName">No Metadata Documentation available.</param>
        public ObjectResult<procGetTrainingRoomDetails_Types> procGetTrainingRoomDetails(global::System.String locationName, global::System.String campusName)
        {
            ObjectParameter locationNameParameter;
            if (locationName != null)
            {
                locationNameParameter = new ObjectParameter("LocationName", locationName);
            }
            else
            {
                locationNameParameter = new ObjectParameter("LocationName", typeof(global::System.String));
            }
    
            ObjectParameter campusNameParameter;
            if (campusName != null)
            {
                campusNameParameter = new ObjectParameter("CampusName", campusName);
            }
            else
            {
                campusNameParameter = new ObjectParameter("CampusName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<procGetTrainingRoomDetails_Types>("procGetTrainingRoomDetails", locationNameParameter, campusNameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="trainingRoomID">No Metadata Documentation available.</param>
        /// <param name="fromDate">No Metadata Documentation available.</param>
        /// <param name="toDate">No Metadata Documentation available.</param>
        public ObjectResult<procRoomAvailability_Types> procRoomAvailability(global::System.String trainingRoomID, Nullable<global::System.DateTime> fromDate, Nullable<global::System.DateTime> toDate)
        {
            ObjectParameter trainingRoomIDParameter;
            if (trainingRoomID != null)
            {
                trainingRoomIDParameter = new ObjectParameter("TrainingRoomID", trainingRoomID);
            }
            else
            {
                trainingRoomIDParameter = new ObjectParameter("TrainingRoomID", typeof(global::System.String));
            }
    
            ObjectParameter fromDateParameter;
            if (fromDate.HasValue)
            {
                fromDateParameter = new ObjectParameter("FromDate", fromDate);
            }
            else
            {
                fromDateParameter = new ObjectParameter("FromDate", typeof(global::System.DateTime));
            }
    
            ObjectParameter toDateParameter;
            if (toDate.HasValue)
            {
                toDateParameter = new ObjectParameter("ToDate", toDate);
            }
            else
            {
                toDateParameter = new ObjectParameter("ToDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<procRoomAvailability_Types>("procRoomAvailability", trainingRoomIDParameter, fromDateParameter, toDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userID">No Metadata Documentation available.</param>
        /// <param name="trainingRoomID">No Metadata Documentation available.</param>
        /// <param name="fromDate">No Metadata Documentation available.</param>
        /// <param name="toDate">No Metadata Documentation available.</param>
        public int procTrainingRoomBlocking(Nullable<global::System.Int32> userID, global::System.String trainingRoomID, Nullable<global::System.DateTime> fromDate, Nullable<global::System.DateTime> toDate)
        {
            ObjectParameter userIDParameter;
            if (userID.HasValue)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.Int32));
            }
    
            ObjectParameter trainingRoomIDParameter;
            if (trainingRoomID != null)
            {
                trainingRoomIDParameter = new ObjectParameter("TrainingRoomID", trainingRoomID);
            }
            else
            {
                trainingRoomIDParameter = new ObjectParameter("TrainingRoomID", typeof(global::System.String));
            }
    
            ObjectParameter fromDateParameter;
            if (fromDate.HasValue)
            {
                fromDateParameter = new ObjectParameter("FromDate", fromDate);
            }
            else
            {
                fromDateParameter = new ObjectParameter("FromDate", typeof(global::System.DateTime));
            }
    
            ObjectParameter toDateParameter;
            if (toDate.HasValue)
            {
                toDateParameter = new ObjectParameter("ToDate", toDate);
            }
            else
            {
                toDateParameter = new ObjectParameter("ToDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction("procTrainingRoomBlocking", userIDParameter, trainingRoomIDParameter, fromDateParameter, toDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="slotID">No Metadata Documentation available.</param>
        public int DeleteBookingDetails(Nullable<global::System.Int32> slotID)
        {
            ObjectParameter slotIDParameter;
            if (slotID.HasValue)
            {
                slotIDParameter = new ObjectParameter("SlotID", slotID);
            }
            else
            {
                slotIDParameter = new ObjectParameter("SlotID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("DeleteBookingDetails", slotIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userID">No Metadata Documentation available.</param>
        public ObjectResult<procGettingBookedDetails_types> procGettingBookedDetails(Nullable<global::System.Int32> userID)
        {
            ObjectParameter userIDParameter;
            if (userID.HasValue)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<procGettingBookedDetails_types>("procGettingBookedDetails", userIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userID">No Metadata Documentation available.</param>
        /// <param name="reviews">No Metadata Documentation available.</param>
        public int uspAddReviews(Nullable<global::System.Int32> userID, global::System.String reviews)
        {
            ObjectParameter userIDParameter;
            if (userID.HasValue)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.Int32));
            }
    
            ObjectParameter reviewsParameter;
            if (reviews != null)
            {
                reviewsParameter = new ObjectParameter("Reviews", reviews);
            }
            else
            {
                reviewsParameter = new ObjectParameter("Reviews", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("uspAddReviews", userIDParameter, reviewsParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<uspGetReviews_Types> uspGetReviews()
        {
            return base.ExecuteFunction<uspGetReviews_Types>("uspGetReviews");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="tblCampu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCampu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCampu object.
        /// </summary>
        /// <param name="campusID">Initial value of the CampusID property.</param>
        /// <param name="locationID">Initial value of the LocationID property.</param>
        public static tblCampu CreatetblCampu(global::System.Int32 campusID, global::System.Int32 locationID)
        {
            tblCampu tblCampu = new tblCampu();
            tblCampu.CampusID = campusID;
            tblCampu.LocationID = locationID;
            return tblCampu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampusID
        {
            get
            {
                return _CampusID;
            }
            set
            {
                if (_CampusID != value)
                {
                    OnCampusIDChanging(value);
                    ReportPropertyChanging("CampusID");
                    _CampusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CampusID");
                    OnCampusIDChanged();
                }
            }
        }
        private global::System.Int32 _CampusID;
        partial void OnCampusIDChanging(global::System.Int32 value);
        partial void OnCampusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CampusName
        {
            get
            {
                return _CampusName;
            }
            set
            {
                OnCampusNameChanging(value);
                ReportPropertyChanging("CampusName");
                _CampusName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CampusName");
                OnCampusNameChanged();
            }
        }
        private global::System.String _CampusName;
        partial void OnCampusNameChanging(global::System.String value);
        partial void OnCampusNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private global::System.Int32 _LocationID;
        partial void OnLocationIDChanging(global::System.Int32 value);
        partial void OnLocationIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TrainingRoomAppDBModel", "FK__tblCampus__Locat__09DE7BCC", "tblLocation")]
        public tblLocation tblLocation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLocation>("TrainingRoomAppDBModel.FK__tblCampus__Locat__09DE7BCC", "tblLocation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLocation>("TrainingRoomAppDBModel.FK__tblCampus__Locat__09DE7BCC", "tblLocation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblLocation> tblLocationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLocation>("TrainingRoomAppDBModel.FK__tblCampus__Locat__09DE7BCC", "tblLocation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblLocation>("TrainingRoomAppDBModel.FK__tblCampus__Locat__09DE7BCC", "tblLocation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="tblLocation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblLocation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblLocation object.
        /// </summary>
        /// <param name="locationID">Initial value of the LocationID property.</param>
        /// <param name="locationName">Initial value of the LocationName property.</param>
        public static tblLocation CreatetblLocation(global::System.Int32 locationID, global::System.String locationName)
        {
            tblLocation tblLocation = new tblLocation();
            tblLocation.LocationID = locationID;
            tblLocation.LocationName = locationName;
            return tblLocation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                if (_LocationID != value)
                {
                    OnLocationIDChanging(value);
                    ReportPropertyChanging("LocationID");
                    _LocationID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocationID");
                    OnLocationIDChanged();
                }
            }
        }
        private global::System.Int32 _LocationID;
        partial void OnLocationIDChanging(global::System.Int32 value);
        partial void OnLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LocationName
        {
            get
            {
                return _LocationName;
            }
            set
            {
                OnLocationNameChanging(value);
                ReportPropertyChanging("LocationName");
                _LocationName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LocationName");
                OnLocationNameChanged();
            }
        }
        private global::System.String _LocationName;
        partial void OnLocationNameChanging(global::System.String value);
        partial void OnLocationNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TrainingRoomAppDBModel", "FK__tblCampus__Locat__09DE7BCC", "tblCampu")]
        public EntityCollection<tblCampu> tblCampus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblCampu>("TrainingRoomAppDBModel.FK__tblCampus__Locat__09DE7BCC", "tblCampu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblCampu>("TrainingRoomAppDBModel.FK__tblCampus__Locat__09DE7BCC", "tblCampu", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="tblReview")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblReview : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblReview object.
        /// </summary>
        /// <param name="reviewId">Initial value of the ReviewId property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="reviews">Initial value of the Reviews property.</param>
        public static tblReview CreatetblReview(global::System.Int32 reviewId, global::System.Int32 userID, global::System.String reviews)
        {
            tblReview tblReview = new tblReview();
            tblReview.ReviewId = reviewId;
            tblReview.UserID = userID;
            tblReview.Reviews = reviews;
            return tblReview;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReviewId
        {
            get
            {
                return _ReviewId;
            }
            set
            {
                if (_ReviewId != value)
                {
                    OnReviewIdChanging(value);
                    ReportPropertyChanging("ReviewId");
                    _ReviewId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReviewId");
                    OnReviewIdChanged();
                }
            }
        }
        private global::System.Int32 _ReviewId;
        partial void OnReviewIdChanging(global::System.Int32 value);
        partial void OnReviewIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Reviews
        {
            get
            {
                return _Reviews;
            }
            set
            {
                OnReviewsChanging(value);
                ReportPropertyChanging("Reviews");
                _Reviews = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Reviews");
                OnReviewsChanged();
            }
        }
        private global::System.String _Reviews;
        partial void OnReviewsChanging(global::System.String value);
        partial void OnReviewsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="tblSlot")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSlot : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSlot object.
        /// </summary>
        /// <param name="slotID">Initial value of the SlotID property.</param>
        public static tblSlot CreatetblSlot(global::System.Int32 slotID)
        {
            tblSlot tblSlot = new tblSlot();
            tblSlot.SlotID = slotID;
            return tblSlot;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SlotID
        {
            get
            {
                return _SlotID;
            }
            set
            {
                if (_SlotID != value)
                {
                    OnSlotIDChanging(value);
                    ReportPropertyChanging("SlotID");
                    _SlotID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SlotID");
                    OnSlotIDChanged();
                }
            }
        }
        private global::System.Int32 _SlotID;
        partial void OnSlotIDChanging(global::System.Int32 value);
        partial void OnSlotIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrainingRoomID
        {
            get
            {
                return _TrainingRoomID;
            }
            set
            {
                OnTrainingRoomIDChanging(value);
                ReportPropertyChanging("TrainingRoomID");
                _TrainingRoomID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TrainingRoomID");
                OnTrainingRoomIDChanged();
            }
        }
        private global::System.String _TrainingRoomID;
        partial void OnTrainingRoomIDChanging(global::System.String value);
        partial void OnTrainingRoomIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FromDate
        {
            get
            {
                return _FromDate;
            }
            set
            {
                OnFromDateChanging(value);
                ReportPropertyChanging("FromDate");
                _FromDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromDate");
                OnFromDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _FromDate;
        partial void OnFromDateChanging(Nullable<global::System.DateTime> value);
        partial void OnFromDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ToDate
        {
            get
            {
                return _ToDate;
            }
            set
            {
                OnToDateChanging(value);
                ReportPropertyChanging("ToDate");
                _ToDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToDate");
                OnToDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ToDate;
        partial void OnToDateChanging(Nullable<global::System.DateTime> value);
        partial void OnToDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="tbltrainingRoomDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbltrainingRoomDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbltrainingRoomDetail object.
        /// </summary>
        /// <param name="trainingRoomID">Initial value of the TrainingRoomID property.</param>
        public static tbltrainingRoomDetail CreatetbltrainingRoomDetail(global::System.String trainingRoomID)
        {
            tbltrainingRoomDetail tbltrainingRoomDetail = new tbltrainingRoomDetail();
            tbltrainingRoomDetail.TrainingRoomID = trainingRoomID;
            return tbltrainingRoomDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TrainingRoomID
        {
            get
            {
                return _TrainingRoomID;
            }
            set
            {
                if (_TrainingRoomID != value)
                {
                    OnTrainingRoomIDChanging(value);
                    ReportPropertyChanging("TrainingRoomID");
                    _TrainingRoomID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TrainingRoomID");
                    OnTrainingRoomIDChanged();
                }
            }
        }
        private global::System.String _TrainingRoomID;
        partial void OnTrainingRoomIDChanging(global::System.String value);
        partial void OnTrainingRoomIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrainingRoomname
        {
            get
            {
                return _TrainingRoomname;
            }
            set
            {
                OnTrainingRoomnameChanging(value);
                ReportPropertyChanging("TrainingRoomname");
                _TrainingRoomname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TrainingRoomname");
                OnTrainingRoomnameChanged();
            }
        }
        private global::System.String _TrainingRoomname;
        partial void OnTrainingRoomnameChanging(global::System.String value);
        partial void OnTrainingRoomnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Block
        {
            get
            {
                return _Block;
            }
            set
            {
                OnBlockChanging(value);
                ReportPropertyChanging("Block");
                _Block = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Block");
                OnBlockChanged();
            }
        }
        private global::System.String _Block;
        partial void OnBlockChanging(global::System.String value);
        partial void OnBlockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Floornumber
        {
            get
            {
                return _Floornumber;
            }
            set
            {
                OnFloornumberChanging(value);
                ReportPropertyChanging("Floornumber");
                _Floornumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Floornumber");
                OnFloornumberChanged();
            }
        }
        private Nullable<global::System.Int32> _Floornumber;
        partial void OnFloornumberChanging(Nullable<global::System.Int32> value);
        partial void OnFloornumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LocationName
        {
            get
            {
                return _LocationName;
            }
            set
            {
                OnLocationNameChanging(value);
                ReportPropertyChanging("LocationName");
                _LocationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LocationName");
                OnLocationNameChanged();
            }
        }
        private global::System.String _LocationName;
        partial void OnLocationNameChanging(global::System.String value);
        partial void OnLocationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CampusName
        {
            get
            {
                return _CampusName;
            }
            set
            {
                OnCampusNameChanging(value);
                ReportPropertyChanging("CampusName");
                _CampusName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CampusName");
                OnCampusNameChanged();
            }
        }
        private global::System.String _CampusName;
        partial void OnCampusNameChanging(global::System.String value);
        partial void OnCampusNameChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="GetLocation_Types")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetLocation_Types : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetLocation_Types object.
        /// </summary>
        /// <param name="locationName">Initial value of the LocationName property.</param>
        /// <param name="locationID">Initial value of the LocationID property.</param>
        public static GetLocation_Types CreateGetLocation_Types(global::System.String locationName, global::System.Int32 locationID)
        {
            GetLocation_Types getLocation_Types = new GetLocation_Types();
            getLocation_Types.LocationName = locationName;
            getLocation_Types.LocationID = locationID;
            return getLocation_Types;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LocationName
        {
            get
            {
                return _LocationName;
            }
            set
            {
                OnLocationNameChanging(value);
                ReportPropertyChanging("LocationName");
                _LocationName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LocationName");
                OnLocationNameChanged();
            }
        }
        private global::System.String _LocationName;
        partial void OnLocationNameChanging(global::System.String value);
        partial void OnLocationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private global::System.Int32 _LocationID;
        partial void OnLocationIDChanging(global::System.Int32 value);
        partial void OnLocationIDChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="procGetCampus_Types")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class procGetCampus_Types : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new procGetCampus_Types object.
        /// </summary>
        /// <param name="campusID">Initial value of the CampusID property.</param>
        /// <param name="campusName">Initial value of the CampusName property.</param>
        public static procGetCampus_Types CreateprocGetCampus_Types(global::System.Int32 campusID, global::System.String campusName)
        {
            procGetCampus_Types procGetCampus_Types = new procGetCampus_Types();
            procGetCampus_Types.CampusID = campusID;
            procGetCampus_Types.CampusName = campusName;
            return procGetCampus_Types;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampusID
        {
            get
            {
                return _CampusID;
            }
            set
            {
                OnCampusIDChanging(value);
                ReportPropertyChanging("CampusID");
                _CampusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CampusID");
                OnCampusIDChanged();
            }
        }
        private global::System.Int32 _CampusID;
        partial void OnCampusIDChanging(global::System.Int32 value);
        partial void OnCampusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CampusName
        {
            get
            {
                return _CampusName;
            }
            set
            {
                OnCampusNameChanging(value);
                ReportPropertyChanging("CampusName");
                _CampusName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CampusName");
                OnCampusNameChanged();
            }
        }
        private global::System.String _CampusName;
        partial void OnCampusNameChanging(global::System.String value);
        partial void OnCampusNameChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="procGettingBookedDetails_types")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class procGettingBookedDetails_types : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new procGettingBookedDetails_types object.
        /// </summary>
        /// <param name="slotID">Initial value of the SlotID property.</param>
        public static procGettingBookedDetails_types CreateprocGettingBookedDetails_types(global::System.Int32 slotID)
        {
            procGettingBookedDetails_types procGettingBookedDetails_types = new procGettingBookedDetails_types();
            procGettingBookedDetails_types.SlotID = slotID;
            return procGettingBookedDetails_types;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SlotID
        {
            get
            {
                return _SlotID;
            }
            set
            {
                OnSlotIDChanging(value);
                ReportPropertyChanging("SlotID");
                _SlotID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlotID");
                OnSlotIDChanged();
            }
        }
        private global::System.Int32 _SlotID;
        partial void OnSlotIDChanging(global::System.Int32 value);
        partial void OnSlotIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrainingRoomID
        {
            get
            {
                return _TrainingRoomID;
            }
            set
            {
                OnTrainingRoomIDChanging(value);
                ReportPropertyChanging("TrainingRoomID");
                _TrainingRoomID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TrainingRoomID");
                OnTrainingRoomIDChanged();
            }
        }
        private global::System.String _TrainingRoomID;
        partial void OnTrainingRoomIDChanging(global::System.String value);
        partial void OnTrainingRoomIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fromdate
        {
            get
            {
                return _fromdate;
            }
            set
            {
                OnfromdateChanging(value);
                ReportPropertyChanging("fromdate");
                _fromdate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fromdate");
                OnfromdateChanged();
            }
        }
        private global::System.String _fromdate;
        partial void OnfromdateChanging(global::System.String value);
        partial void OnfromdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String todate
        {
            get
            {
                return _todate;
            }
            set
            {
                OntodateChanging(value);
                ReportPropertyChanging("todate");
                _todate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("todate");
                OntodateChanged();
            }
        }
        private global::System.String _todate;
        partial void OntodateChanging(global::System.String value);
        partial void OntodateChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="procGetTrainingRoomDetails_Types")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class procGetTrainingRoomDetails_Types : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new procGetTrainingRoomDetails_Types object.
        /// </summary>
        /// <param name="trainingRoomID">Initial value of the TrainingRoomID property.</param>
        /// <param name="trainingRoomname">Initial value of the TrainingRoomname property.</param>
        /// <param name="floornumber">Initial value of the Floornumber property.</param>
        /// <param name="block">Initial value of the Block property.</param>
        public static procGetTrainingRoomDetails_Types CreateprocGetTrainingRoomDetails_Types(global::System.String trainingRoomID, global::System.String trainingRoomname, global::System.Int32 floornumber, global::System.String block)
        {
            procGetTrainingRoomDetails_Types procGetTrainingRoomDetails_Types = new procGetTrainingRoomDetails_Types();
            procGetTrainingRoomDetails_Types.TrainingRoomID = trainingRoomID;
            procGetTrainingRoomDetails_Types.TrainingRoomname = trainingRoomname;
            procGetTrainingRoomDetails_Types.Floornumber = floornumber;
            procGetTrainingRoomDetails_Types.Block = block;
            return procGetTrainingRoomDetails_Types;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TrainingRoomID
        {
            get
            {
                return _TrainingRoomID;
            }
            set
            {
                OnTrainingRoomIDChanging(value);
                ReportPropertyChanging("TrainingRoomID");
                _TrainingRoomID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TrainingRoomID");
                OnTrainingRoomIDChanged();
            }
        }
        private global::System.String _TrainingRoomID;
        partial void OnTrainingRoomIDChanging(global::System.String value);
        partial void OnTrainingRoomIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TrainingRoomname
        {
            get
            {
                return _TrainingRoomname;
            }
            set
            {
                OnTrainingRoomnameChanging(value);
                ReportPropertyChanging("TrainingRoomname");
                _TrainingRoomname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TrainingRoomname");
                OnTrainingRoomnameChanged();
            }
        }
        private global::System.String _TrainingRoomname;
        partial void OnTrainingRoomnameChanging(global::System.String value);
        partial void OnTrainingRoomnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Floornumber
        {
            get
            {
                return _Floornumber;
            }
            set
            {
                OnFloornumberChanging(value);
                ReportPropertyChanging("Floornumber");
                _Floornumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Floornumber");
                OnFloornumberChanged();
            }
        }
        private global::System.Int32 _Floornumber;
        partial void OnFloornumberChanging(global::System.Int32 value);
        partial void OnFloornumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Block
        {
            get
            {
                return _Block;
            }
            set
            {
                OnBlockChanging(value);
                ReportPropertyChanging("Block");
                _Block = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Block");
                OnBlockChanged();
            }
        }
        private global::System.String _Block;
        partial void OnBlockChanging(global::System.String value);
        partial void OnBlockChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="procRoomAvailability_Types")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class procRoomAvailability_Types : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new procRoomAvailability_Types object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="trainingRoomID">Initial value of the TrainingRoomID property.</param>
        /// <param name="fromDate">Initial value of the FromDate property.</param>
        /// <param name="toDate">Initial value of the ToDate property.</param>
        public static procRoomAvailability_Types CreateprocRoomAvailability_Types(global::System.Int32 userID, global::System.String trainingRoomID, global::System.DateTime fromDate, global::System.DateTime toDate)
        {
            procRoomAvailability_Types procRoomAvailability_Types = new procRoomAvailability_Types();
            procRoomAvailability_Types.UserID = userID;
            procRoomAvailability_Types.TrainingRoomID = trainingRoomID;
            procRoomAvailability_Types.FromDate = fromDate;
            procRoomAvailability_Types.ToDate = toDate;
            return procRoomAvailability_Types;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TrainingRoomID
        {
            get
            {
                return _TrainingRoomID;
            }
            set
            {
                OnTrainingRoomIDChanging(value);
                ReportPropertyChanging("TrainingRoomID");
                _TrainingRoomID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TrainingRoomID");
                OnTrainingRoomIDChanged();
            }
        }
        private global::System.String _TrainingRoomID;
        partial void OnTrainingRoomIDChanging(global::System.String value);
        partial void OnTrainingRoomIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FromDate
        {
            get
            {
                return _FromDate;
            }
            set
            {
                OnFromDateChanging(value);
                ReportPropertyChanging("FromDate");
                _FromDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromDate");
                OnFromDateChanged();
            }
        }
        private global::System.DateTime _FromDate;
        partial void OnFromDateChanging(global::System.DateTime value);
        partial void OnFromDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ToDate
        {
            get
            {
                return _ToDate;
            }
            set
            {
                OnToDateChanging(value);
                ReportPropertyChanging("ToDate");
                _ToDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToDate");
                OnToDateChanged();
            }
        }
        private global::System.DateTime _ToDate;
        partial void OnToDateChanging(global::System.DateTime value);
        partial void OnToDateChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TrainingRoomAppDBModel", Name="uspGetReviews_Types")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class uspGetReviews_Types : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new uspGetReviews_Types object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="reviews">Initial value of the Reviews property.</param>
        public static uspGetReviews_Types CreateuspGetReviews_Types(global::System.Int32 userID, global::System.String reviews)
        {
            uspGetReviews_Types uspGetReviews_Types = new uspGetReviews_Types();
            uspGetReviews_Types.UserID = userID;
            uspGetReviews_Types.Reviews = reviews;
            return uspGetReviews_Types;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Reviews
        {
            get
            {
                return _Reviews;
            }
            set
            {
                OnReviewsChanging(value);
                ReportPropertyChanging("Reviews");
                _Reviews = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Reviews");
                OnReviewsChanged();
            }
        }
        private global::System.String _Reviews;
        partial void OnReviewsChanging(global::System.String value);
        partial void OnReviewsChanged();

        #endregion
    }

    #endregion
    
}
